language: python

dist: xenial


addons:
    apt:
        packages:
            - libxkbcommon-x11-0  # for PyQt 5.12
            - libxcb-icccm4
            - libxcb-image0
            - libxcb-keysyms1
            - libxcb-randr0
            - libxcb-render-util0
            - libxcb-xinerama0

matrix:
    include:
#        - &python36
#          python: '3.6'
#          env: ORANGE="release"
#        - &python37
#          python: '3.7'
#          env: ORANGE="release"
        - &master
          python: '3.7'
          env: ORANGE="master"

cache:
    apt: true   # does not work for public repos
    directories:
        - $HOME/.cache/pip
        - $HOME/.ccache
        - $TRAVIS_BUILD_DIR/pyqt

before_cache:   # prevent logs from caching
    - rm -f $HOME/.cache/pip/log/debug.log

before_install:
    - source $TRAVIS_BUILD_DIR/.travis/util.sh
    - pip install -U setuptools pip wheel
    - pip install codecov
    # Orange requires numpy>=1.16 but cannot update it itself
    # matplotlib needs certifi>=2020.06.20 but cannot update it itself
    - pip install -U numpy certifi
    - pip install --ignore-installed gensim
    - mkdir -p /home/travis/.local/share/Orange  # create orange app dir

install:
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - python setup.py develop   # assure version.py is present; required for imports

script:
    - XVFBARGS="-screen 0 1280x1024x24"
    - catchsegv xvfb-run -a -s "$XVFBARGS" coverage run setup.py test

after_success:
    - codecov
